version: '3.9'

services:
  db:
    image: postgres
    ports:
      - "4321:5432"
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'graphql_postgresql'
  server:
    build: .
    depends_on:
      - db
    ports: 
      - "8002:3000"

